Vagrant.configure("2") do |config|

  # Função para definir uma VM.

  def define_vm(config, name, box_manager, ip_suffix)
    config.vm.define name do |vm| # Define a VM com um nome específico.
      vm.vm.box = box_manager # Define a imagem da VM.
      # O Vagrant, por padrão, cria uma máquina virtual com um espaço
      # de armazenamento com cerca de 10GB
      # Para alterar o tamanho do armazenamento, você pode usar o plugin vagrant-disksize
      # (vagrant plugin install vagrant-disksize)
      # vm.vm.disksize.size = '50GB'
      vm.vm.provider "virtualbox" do |vb| # Configurações específicas do virtualbox.
        vb.name = name # Nome da VM no virtualbox.
        vb.memory = 2048 # Define a memória RAM para 2048 MB
        vb.cpus = 2 # Define o número de CPUs(Processador) para 2
      end
      # Configura a VM para usar a rede pública (equivalente a uma configuração de rede em modo bridge)
      vm.vm.network "public_network", ip: "192.168.1.#{ip_suffix}"
    end
  end

  # Hash com as boxes e gerenciadores de pacotes para diferentes distribuições Linux.
  rhel9_box = 'generic/rhel9'
  rhel8_box = 'generic/rhel8'
  rhel7_box = 'generic/rhel7'
  opensuse42_box = 'generic/opensuse42'

  # Servidores BRASIL
  br_vms = {
    'brlnx01' => rhel9_box,
    'brlnx02' => rhel8_box,
    'brlnx03' => rhel7_box,
    'brlnx04' => opensuse42_box
  }

  # Servidores PORTUGAL
  pt_vms = {
    'ptlnx01' => rhel9_box,
    'ptlnx02' => rhel8_box,
    'ptlnx03' => rhel7_box,
    'ptlnx04' => opensuse42_box
  }

  # Define VMs com diferentes distribuições Linux.
  ip_suffix = 101
  br_vms.each do |name, box| # BRASIL
    define_vm(config, name, box, ip_suffix)
    ip_suffix += 1
  end

  pt_vms.each do |name, box| # PORTUGAL
    define_vm(config, name, box, ip_suffix)
    ip_suffix += 1
  end
end